---
details:
    header: Kasia Lukasik
    description: ˈkaɕa
    email: katarzynalukasik2@gmail.com
    email_link: mailto:katarzynalukasik2@gmail.com
    instagram: Instagram
    instagram_link: https://www.instagram.com/ka_luka_sik/
    footer: © Kasia Lukasik 2020